{{- range .Values.k8up.backup.namespaces }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-{{ . }}
  namespace: {{ . }}
spec:
  repoPasswordSecretRef:
    name: {{ . }}-repo
    key: password
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
{{- end }}