{{- range $namespace := .Values.k8up.backup.namespaces }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-{{ $namespace }}
  namespace: {{ $namespace }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $namespace }}-repo
      key: password
    s3:
      endpoint: {{ .Values.k8up.s3.endpoint }}
      bucket: k8s-backup/{{ $namespace }}
      accessKeyIDSecretRef:
        name: k8up-s3-creds
        key: username
      secretAccessKeySecretRef:
        name: k8up-s3-creds
        key: password
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
{{- end }}