{{- range $namespace := .Values.k8up.backup.namespaces }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-{{ $namespace }}
  namespace: {{ $namespace }}
spec:
  backend:
    repoPasswordSecretRef:
      name: {{ $namespace }}-repo
      key: password
    s3:
      endpoint: {{ $.Values.k8up.backup.s3.endpoint }}
      bucket: {{ $.Values.k8up.backup.s3.bucket }}/{{ $namespace }}
      accessKeyIDSecretRef:
        name: {{ $namespace }}-s3-secret
        key: username
      secretAccessKeySecretRef:
        name: {{ $namespace }}-s3-secret
        key: password
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
---
{{- end }}
