{{- if .Values.k8up.backup.namespaces }}
{{- range .Values.gameServer.ports.tcp }}
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: k8up-{{ .Values.k8up.backup.namespaces }}
  namespace: {{ .Values.k8up.backup.namespaces }}
spec:
  repoPasswordSecretRef:
    name: {{ .Values.k8up.backup.namespaces }}-repo
    key: password
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
{{- end }}
{{- end }}