{{- if .Values.k8up.backup.namespaces }}
{{- range .Values.k8up.backup.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.k8up.backup.namespaces }}-repo
type: Opaque
stringData:
  password: {{ .Values.k8up.backup.namespaces }}-repo-secret
{{- end }}
{{- end }}