{{- range $namespace := .Values.k8up.backup.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $namespace }}-repo
  namespace: {{ $namespace }}
type: Opaque
stringData:
  password: {{ $namespace }}-repo-secret
---
{{- end }}
