{{- range .Values.k8up.backup.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ . }}-repo
  namespace: {{ . }}
type: Opaque
stringData:
  password: {{ . }}-repo-secret
{{- end }}