{{- range $namespace := .Values.k8up.backup.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $namespace }}-s3-secret
  namespace: 
type: Opaque
stringData:
  username: {{ $.Values.k8up.backup.s3.accessKey }}
  password: {{ $.Values.k8up.backup.s3.accessSecret }}
{{- end }}